services:
    bb3mobi.imgposts.listener:
        class: bb3mobi\imgposts\event\listener
        arguments:
            - @template
            - @config
            - @dbal.conn
            - %core.root_path%
            - @bb3mobi.imgposts.helper
        tags:
            - { name: event.listener }
    bb3mobi.imgposts.helper:
        class: bb3mobi\imgposts\core\helper
        arguments:
            - @template
            - @log
            - @config
            - @user
            - @auth
            - @dbal.conn
            - %core.root_path%
            - %core.php_ext%

    bb3mobi.imgposts.cron.task.tidy_images:
        class: bb3mobi\imgposts\cron\task\tidy_images
        arguments:
            - @config
            - @log
            - @user
            - @template
            - @auth
            - @dbal.conn
            - %core.root_path%
            - %core.php_ext%

        calls:
            - [set_name, [cron.task.core.bb3mobi_tidy_images]]
        tags:
            - { name: cron.task }
